### ISSUE TITLE
spec should allow empty slot for an intent

### ISSUE THREAD

**Issue by DreamerMind** [DreamerMind/snips-app-helpers#1]
Right now when we write:
```yaml
coverage:
   MyIntent:
   MySecondIntent:
        - ["slot_1", "+"]
```
MyIntent will rise a warning in spec checker since it was suposed to be a capture any slot sequence behaviour. It should be changed to a there is no slot.
And  the any slot could be represented as:
```
["*", "*"]
```
